
stages:
  - build
  - release

build:
  stage: build
  image:
    name: node:10
  script:
    - npm test

release:
  stage: release
  only:
    - tags
  image:
    name: node:10
  script:
    - npm publish